// Code generated by protoc-gen-go. DO NOT EDIT.
// source: websocket-push-go.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushChRequest struct {
	Ch                   string   `protobuf:"bytes,1,opt,name=ch,proto3" json:"ch,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushChRequest) Reset()         { *m = PushChRequest{} }
func (m *PushChRequest) String() string { return proto.CompactTextString(m) }
func (*PushChRequest) ProtoMessage()    {}
func (*PushChRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_253cb561c86a6bc2, []int{0}
}

func (m *PushChRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushChRequest.Unmarshal(m, b)
}
func (m *PushChRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushChRequest.Marshal(b, m, deterministic)
}
func (m *PushChRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushChRequest.Merge(m, src)
}
func (m *PushChRequest) XXX_Size() int {
	return xxx_messageInfo_PushChRequest.Size(m)
}
func (m *PushChRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushChRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushChRequest proto.InternalMessageInfo

func (m *PushChRequest) GetCh() string {
	if m != nil {
		return m.Ch
	}
	return ""
}

func (m *PushChRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type PushChReply struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushChReply) Reset()         { *m = PushChReply{} }
func (m *PushChReply) String() string { return proto.CompactTextString(m) }
func (*PushChReply) ProtoMessage()    {}
func (*PushChReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_253cb561c86a6bc2, []int{1}
}

func (m *PushChReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushChReply.Unmarshal(m, b)
}
func (m *PushChReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushChReply.Marshal(b, m, deterministic)
}
func (m *PushChReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushChReply.Merge(m, src)
}
func (m *PushChReply) XXX_Size() int {
	return xxx_messageInfo_PushChReply.Size(m)
}
func (m *PushChReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushChReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushChReply proto.InternalMessageInfo

func (m *PushChReply) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type PushAllRequest struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushAllRequest) Reset()         { *m = PushAllRequest{} }
func (m *PushAllRequest) String() string { return proto.CompactTextString(m) }
func (*PushAllRequest) ProtoMessage()    {}
func (*PushAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_253cb561c86a6bc2, []int{2}
}

func (m *PushAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushAllRequest.Unmarshal(m, b)
}
func (m *PushAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushAllRequest.Marshal(b, m, deterministic)
}
func (m *PushAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushAllRequest.Merge(m, src)
}
func (m *PushAllRequest) XXX_Size() int {
	return xxx_messageInfo_PushAllRequest.Size(m)
}
func (m *PushAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushAllRequest proto.InternalMessageInfo

func (m *PushAllRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type PushAllReply struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushAllReply) Reset()         { *m = PushAllReply{} }
func (m *PushAllReply) String() string { return proto.CompactTextString(m) }
func (*PushAllReply) ProtoMessage()    {}
func (*PushAllReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_253cb561c86a6bc2, []int{3}
}

func (m *PushAllReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushAllReply.Unmarshal(m, b)
}
func (m *PushAllReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushAllReply.Marshal(b, m, deterministic)
}
func (m *PushAllReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushAllReply.Merge(m, src)
}
func (m *PushAllReply) XXX_Size() int {
	return xxx_messageInfo_PushAllReply.Size(m)
}
func (m *PushAllReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushAllReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushAllReply proto.InternalMessageInfo

func (m *PushAllReply) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*PushChRequest)(nil), "proto.PushChRequest")
	proto.RegisterType((*PushChReply)(nil), "proto.PushChReply")
	proto.RegisterType((*PushAllRequest)(nil), "proto.PushAllRequest")
	proto.RegisterType((*PushAllReply)(nil), "proto.PushAllReply")
}

func init() {
	proto.RegisterFile("websocket-push-go.proto", fileDescriptor_253cb561c86a6bc2)
}

var fileDescriptor_253cb561c86a6bc2 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x4f, 0x4d, 0x2a,
	0xce, 0x4f, 0xce, 0x4e, 0x2d, 0xd1, 0x2d, 0x28, 0x2d, 0xce, 0xd0, 0x4d, 0xcf, 0xd7, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x96, 0x5c, 0xbc, 0x01, 0xa5, 0xc5, 0x19, 0xce,
	0x19, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0xc9, 0x19, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0xc9, 0x19, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5,
	0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x30, 0xae, 0x92, 0x3a, 0x17, 0x37,
	0x4c, 0x6b, 0x41, 0x4e, 0x25, 0xb2, 0x42, 0x46, 0x54, 0x85, 0x5a, 0x5c, 0x7c, 0x20, 0x85, 0x8e,
	0x39, 0x39, 0x30, 0x4b, 0x70, 0xab, 0xd5, 0xe0, 0xe2, 0x81, 0xab, 0xc5, 0x6b, 0xaa, 0x51, 0x39,
	0x17, 0x5b, 0x78, 0x31, 0x48, 0xad, 0x90, 0x09, 0x17, 0x1b, 0xc4, 0x21, 0x42, 0x22, 0x10, 0xcf,
	0xe9, 0xa1, 0x78, 0x49, 0x4a, 0x08, 0x4d, 0xb4, 0x20, 0xa7, 0x52, 0x89, 0x41, 0xc8, 0x9c, 0x8b,
	0x1d, 0x6a, 0x93, 0x90, 0x28, 0x92, 0x02, 0x84, 0x2b, 0xa5, 0x84, 0xd1, 0x85, 0xc1, 0x1a, 0x93,
	0xd8, 0xc0, 0xa2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x36, 0xf9, 0xbe, 0x5b, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WsPushClient is the client API for WsPush service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WsPushClient interface {
	// 推送到频道
	PushCh(ctx context.Context, in *PushChRequest, opts ...grpc.CallOption) (*PushChReply, error)
	// 推送给所有用户
	PushAll(ctx context.Context, in *PushAllRequest, opts ...grpc.CallOption) (*PushAllReply, error)
}

type wsPushClient struct {
	cc grpc.ClientConnInterface
}

func NewWsPushClient(cc grpc.ClientConnInterface) WsPushClient {
	return &wsPushClient{cc}
}

func (c *wsPushClient) PushCh(ctx context.Context, in *PushChRequest, opts ...grpc.CallOption) (*PushChReply, error) {
	out := new(PushChReply)
	err := c.cc.Invoke(ctx, "/proto.WsPush/PushCh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wsPushClient) PushAll(ctx context.Context, in *PushAllRequest, opts ...grpc.CallOption) (*PushAllReply, error) {
	out := new(PushAllReply)
	err := c.cc.Invoke(ctx, "/proto.WsPush/PushAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WsPushServer is the server API for WsPush service.
type WsPushServer interface {
	// 推送到频道
	PushCh(context.Context, *PushChRequest) (*PushChReply, error)
	// 推送给所有用户
	PushAll(context.Context, *PushAllRequest) (*PushAllReply, error)
}

// UnimplementedWsPushServer can be embedded to have forward compatible implementations.
type UnimplementedWsPushServer struct {
}

func (*UnimplementedWsPushServer) PushCh(ctx context.Context, req *PushChRequest) (*PushChReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushCh not implemented")
}
func (*UnimplementedWsPushServer) PushAll(ctx context.Context, req *PushAllRequest) (*PushAllReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushAll not implemented")
}

func RegisterWsPushServer(s *grpc.Server, srv WsPushServer) {
	s.RegisterService(&_WsPush_serviceDesc, srv)
}

func _WsPush_PushCh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushChRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsPushServer).PushCh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WsPush/PushCh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsPushServer).PushCh(ctx, req.(*PushChRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WsPush_PushAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsPushServer).PushAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WsPush/PushAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsPushServer).PushAll(ctx, req.(*PushAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WsPush_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WsPush",
	HandlerType: (*WsPushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushCh",
			Handler:    _WsPush_PushCh_Handler,
		},
		{
			MethodName: "PushAll",
			Handler:    _WsPush_PushAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "websocket-push-go.proto",
}
